// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqmczdhxtyinnphyspav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxbWN6ZGh4dHlpbm5waHlzcGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTk0NDYsImV4cCI6MjA2NjE5NTQ0Nn0.ly9YV5e1G1bXWsg3JYo_psMgoCyJr8oBmvMNW0Qtx2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);